import React, { useEffect, useMemo, useState } from "react";
import { Card, CardContent } from "./components/ui/card";
import { Input } from "./components/ui/input";
import { Badge } from "./components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "./components/ui/table";
import { Tabs, TabsList, TabsTrigger } from "./components/ui/tabs";
import { motion } from "framer-motion";
// import { Button } from "./components/ui/button";
// import { Textarea } from "./components/ui/textarea";
// import { Checkbox } from "./components/ui/checkbox";
// import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "./components/ui/dialog";
// import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetTrigger } from "./components/ui/sheet";
// import { ScrollArea } from "./components/ui/scroll-area";
import { Download, Upload, Plus, Pencil, Trash2, Filter as FilterIcon, Search, Library, Gamepad2, ArrowDownWideNarrow, ExternalLink } from "lucide-react";

// --- 型定義 ---
export type GameItem = {
  id: string;
  hardware: string;       // ハード名
  title: string;          // ゲーム名
  keyword: string;        // 検索用キーワード
  completed: boolean;     // クリアしたかどうか
  achievement?: string;   // （任意）誇れる要素
  playtime: number;       // プレイ時間
  archive_url?: string;   // （任意）配信アーカイブのURL
  notes?: string;         // （任意）一言メモ
  release_date: number;   // リリース日
  createdAt: number;
};

// --- サンプルデータ（初期表示用） ---
const seedData: GameItem[] = [
  {
    id: crypto.randomUUID(),
    hardware: "SFC",
    title: "稲妻サーブだ! スーパービーチバレー",
    keyword: "稲妻さーぶだ! すーぱーびーちばれー",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "https://www.youtube.com/watch?v=LQlDa6ESOvM",
    notes: "魔球の入力方法を知りたかった",
    release_date: new Date("1995-08-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "SFC",
    title: "SUPER桃太郎電鉄DX",
    keyword: "SUPER桃太郎電鉄dx,桃鉄dx,ももてつdx",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("1995-12-08").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "SFC",
    title: "ファイナルファイト 2",
    keyword: "ふぁいなるふぁいと2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "アンドレ😰",
    release_date: new Date("1993-05-22").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "SFC",
    title: "スーパーファミスタ 5",
    keyword: "すーぱーふぁみすた5,ふぁみすた5",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "イチローでランニングHR",
    release_date: new Date("1996-02-29").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GB",
    title: "ポケットモンスター 金",
    keyword: "ぽけっともんすたー金,ぽけもん金,ぽけっともんすたーきん,ぽけもんきん",
    completed: true,
    achievement: "クリア",
    playtime: 63,
    archive_url: "",
    notes: "初ポケモン",
    release_date: new Date("1999-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GB",
    title: "ONEPIECE 夢のルフィ海賊団誕生!",
    keyword: "ONEPIECE,夢のるふぃ海賊団誕生,わんぴーす",
    completed: false,
    achievement: "",
    playtime: 30,
    archive_url: "",
    notes: "",
    release_date: new Date("2001-04-27").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GB",
    title: "筋肉番付GB 2 〜目指せ！マッスルチャンピオン〜",
    keyword: "筋肉番付,きんにくばんづけ",
    completed: false,
    achievement: "",
    playtime: 30,
    archive_url: "",
    notes: "",
    release_date: new Date("2000-08-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GBA",
    title: "ロックマンエグゼ 2",
    keyword: "ろっくまんえぐぜ2",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2001-12-14").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GBA",
    title: "ロックマンエグゼ 4 ブルームーン",
    keyword: "ろっくまんえぐぜ4,ぶるーむーん",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2003-12-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GBA",
    title: "ポケットモンスター ルビー",
    keyword: "ぽけっともんすたーるびー,ぽけもんるびー,るびさふぁ",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2002-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GBA",
    title: "ポケットモンスター サファイア",
    keyword: "ぽけっともんすたーさふぁいあ,ぽけもんさふぁいあ,るびさふぁ",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2002-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GBA",
    title: "ポケットモンスター ファイアレッド",
    keyword: "ぽけっともんすたーふぁいあれっど,ぽけもんふぁいあれっど,fr",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2004-01-29").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GBA",
    title: "ワリオランドアドバンス ヨーキのお宝",
    keyword: "わりおらんどあどばんす,よーきのお宝,よーきのおたから",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2001-08-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "大乱闘スマッシュブラザーズDX",
    keyword: "大乱闘すまっしゅぶらざーずdx,すまぶらdx",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2001-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "マリオパーティ 4",
    keyword: "まりおぱーてぃ4,まりぱ4",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "ぱらぱらブック",
    release_date: new Date("2002-11-08").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "マリオカート ダブルダッシュ!!",
    keyword: "まりおかーと,だぶるだっしゅ,まりかー",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2003-11-07").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "スーパーマリオサンシャイン",
    keyword: "すーぱーまりおさんしゃいん",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "途中でやめた",
    release_date: new Date("2002-07-19").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "どうぶつの森e+",
    keyword: "どうぶつの森e+,どう森,ぶつ森,どうぶつのもりいーぷらす,どうもり,ぶつもり",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2003-06-27").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "カービィのエアライド",
    keyword: "かーびぃのえあらいど",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "ハイドラ",
    release_date: new Date("2003-07-11").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "ポケモンコロシアム",
    keyword: "ぽけもんころしあむ",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2003-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "NARUTO 激闘忍者大戦! 2",
    keyword: "naruto,なると激闘忍者大戦2,激忍2,げきにん2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "我愛羅",
    release_date: new Date("2003-12-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "NARUTO 激闘忍者大戦! 4",
    keyword: "naruto,なると激闘忍者大戦4,激忍4,げきにん4",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "三代目火影",
    release_date: new Date("2005-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "ゼルダの伝説 時のオカリナ",
    keyword: "ぜるだの伝説,時のおかりな,時おか,ときおか",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2002-11-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "GC",
    title: "ZOIDS VS. III",
    keyword: "zoids,ぞいどばーさす3",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "ライガーゼロイクス",
    release_date: new Date("2004-09-30").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "ポケモンレンジャー",
    keyword: "ぽけもんれんじゃー,ぽけれん",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2006-03-23").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "ニンテンドッグス 柴&フレンズ",
    keyword: "にんてんどっぐす,しばあんどふれんず",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "ミニチュアピンシャー×3",
    release_date: new Date("2005-04-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "たまごっちのプチプチおみせっち",
    keyword: "たまごっちのぷちぷちおみせっち",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2005-09-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "おいでよ どうぶつの森",
    keyword: "おいでよどうぶつの森,おい森,ぶつ森,おいでよどうぶつのもり,おいもり,ぶつもり",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2005-11-23").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "伝説のスタフィー たいけつ!ダイール海賊団",
    keyword: "でんせつのすたふぃー,すたふぃー",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2008-07-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "遊☆戯☆王デュエルモンスターズ NIGHTMARE TROUBADOUR",
    keyword: "遊戯王,ゆうぎおう,ないとめあとらばどーる",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2005-07-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "脳を鍛える大人のDSトレーニング",
    keyword: "脳を鍛える大人のdsとれーにんぐ,脳とれ,のうをきたえるおとなのdsとれーにんぐ,のうとれ",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2005-05-19").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "ポケットモンスター ハートゴールド",
    keyword: "ぽけっともんすたーはーとごーるど,ぽけもんはーとごーるど,hgss",
    completed: true,
    achievement: "",
    playtime: 63,
    archive_url: "",
    notes: "",
    release_date: new Date("2009-09-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "ドラゴンクエストV 天空の花嫁",
    keyword: "どらごんくえすと5,どらくえ5,dq5",
    completed: true,
    achievement: "",
    playtime: 50,
    archive_url: "",
    notes: "デボラ,チロル",
    release_date: new Date("2008-07-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "ドラゴンクエストIX 星空の守り人",
    keyword: "どらごんくえすと9,どらくえ9,dq9",
    completed: true,
    achievement: "",
    playtime: 50,
    archive_url: "",
    notes: "",
    release_date: new Date("2009-07-11").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "DS",
    title: "ドラゴンクエストモンスターズ ジョーカー2",
    keyword: "どらごんくえすともんすたーずじょーかー2,どらくえもんすたーずじょーかー2,dqm2",
    completed: true,
    achievement: "",
    playtime: 17,
    archive_url: "",
    notes: "",
    release_date: new Date("2010-04-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "モンスターハンター 3G",
    keyword: "もんすたーはんたー3g,もんはん3g,mh3g",
    completed: false,
    achievement: "",
    playtime: 318,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-12-06").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "ブレイブリーデフォルト フライングフェアリー たっぷり無料で遊べる版",
    keyword: "ぶれいぶりーでふぉるとふらいんぐふぇありー,bdff",
    completed: false,
    achievement: "",
    playtime: 59,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-10-11").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "とびだせ どうぶつの森",
    keyword: "とびだせどうぶつの森,とび森,ぶつ森,とびだせどうぶつのもり,とびもり,ぶつもり",
    completed: false,
    achievement: "",
    playtime: 241,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-11-08").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "モンスターハンター 4",
    keyword: "もんすたーはんたー4,もんはん4,mh4",
    completed: false,
    achievement: "",
    playtime: 153,
    archive_url: "",
    notes: "操虫棍",
    release_date: new Date("2013-09-14").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "モンスターハンター ダブルクロス",
    keyword: "もんすたーはんたーだぶるくろす,もんはんだぶるくろす,もんはんxx,mhxx",
    completed: false,
    achievement: "",
    playtime: 145,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-03-18").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "ポケットモンスター X",
    keyword: "ぽけっともんすたーx,ぽけもんx,xy",
    completed: true,
    achievement: "クリア",
    playtime: 166,
    archive_url: "",
    notes: "",
    release_date: new Date("2013-10-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "ポケットモンスター オメガルビー",
    keyword: "ぽけっともんすたーおめがるびー,ぽけもんおめがるびー,oras,るびさふぁ",
    completed: true,
    achievement: "クリア",
    playtime: 61,
    archive_url: "",
    notes: "",
    release_date: new Date("2014-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "3DS",
    title: "ポケットモンスター ウルトラサン",
    keyword: "ぽけっともんすたーさん,ぽけもんさん,さんむーん,sm",
    completed: true,
    achievement: "クリア",
    playtime: 122,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-11-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "ポケットモンスター Let's Go! イーブイ",
    keyword: "ぽけもんれっつごーいーぶい,ぴかぶい",
    completed: true,
    achievement: "クリア",
    playtime: 30,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-11-16").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "ポケットモンスター ソード",
    keyword: "ぽけっともんすたーそーど,ぽけもんそーど,けんたて,剣盾",
    completed: true,
    achievement: "クリア",
    playtime: 200,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-11-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "Pokémon LEGENDS アルセウス",
    keyword: ",ぽけもんれじぇんずあるせうす,",
    completed: true,
    achievement: "クリア",
    playtime: 90,
    archive_url: "",
    notes: "",
    release_date: new Date("2022-01-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "Pokémon UNITE",
    keyword: "ぽけもんゆないと,ぽけゆな",
    completed: false,
    achievement: "最高マスター1800辺り",
    playtime: 710,
    archive_url: "",
    notes: "",
    release_date: new Date("2021-07-21").getTime(),
    createdAt: Date.now(),
  },
    {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "あつまれ どうぶつの森",
    keyword: "あつまれどうぶつの森,あつ森,ぶつ森,あつまれどうぶつのもり,あつもり,ぶつもり",
    completed: false,
    achievement: "",
    playtime: 275,
    archive_url: "",
    notes: "",
    release_date: new Date("2020-03-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "ゼルダの伝説 ブレス オブ ザ ワイルド",
    keyword: "ぜるだの伝説ぶれすおぶざわいるど,ぜるだのでんせつぶれすおぶざわいるど,ぶれわい,botw,bow",
    completed: false,
    achievement: "",
    playtime: 35,
    archive_url: "",
    notes: "ガノン城で止まってる",
    release_date: new Date("2017-03-03").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "マリオカート 8 デラックス",
    keyword: "まりおかーと8でらっくす,まりか8dx,まりかー8dx",
    completed: false,
    achievement: "",
    playtime: 30,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-04-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "ドラゴンクエストXI 過ぎ去りし時を求めて S",
    keyword: "どらごんくえすと11過ぎ去りし時を求めてs,どらごんくえすと11すぎさりしときをもとめてs,どらくえ11s,dq11s",
    completed: true,
    achievement: "",
    playtime: 137,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-09-27").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "ゼノブレイド 2",
    keyword: "ぜのぶれいど2,ぜのぶれ2,ぜの2",
    completed: true,
    achievement: "クリア",
    playtime: 80,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-12-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "ブレイブリーデフォルト 2",
    keyword: "ぶれいぶりーでふぉると2,bd2",
    completed: true,
    achievement: "クリア",
    playtime: 60,
    archive_url: "",
    notes: "",
    release_date: new Date("2021-02-26").getTime(),
    createdAt: Date.now(),
  },
    {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "ヒューマン フォール フラット",
    keyword: "ひゅーまんふぉーるふらっと,hff",
    completed: false,
    achievement: "",
    playtime: 10,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-12-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "モンスターハンターライズ:サンブレイク",
    keyword: "もんすたーはんたーらいず:さんぶれいく,もんはんらいず,もんはんさんぶれいく,mhrs",
    completed: false,
    achievement: "",
    playtime: 450,
    archive_url: "",
    notes: "弓",
    release_date: new Date("2022-06-30").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Switch",
    title: "スプラトゥーン2",
    keyword: "すぷらとぅーん2",
    completed: false,
    achievement: "A+からS辺り",
    playtime: 515,
    archive_url: "",
    notes: "パブローラー",
    release_date: new Date("2017-07-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "サルゲッチュP!",
    keyword: "さるげっちゅp!",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2005-03-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "モンスターハンターポータブル 2nd",
    keyword: "もんすたーはんたーぽーたぶる2nd,もんはん2nd,mhp2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "初モンハン",
    release_date: new Date("2007-02-22").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "モンスターハンターポータブル 2ndG",
    keyword: "もんすたーはんたーぽーたぶる2ndg,もんはん2ndg,mhp2g",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2008-03-27").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "モンスターハンターポータブル 3rd",
    keyword: "もんすたーはんたーぽーたぶる3rd,もんはん3rd,mhp3rd",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2010-12-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "ワールド・ネバーランド ククリア王国物語",
    keyword: "わーるどねばーらんどくくりあ王国物語,わーねば",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-02-16").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "勇者のくせになまいきだor2",
    keyword: "勇者のくせになまいきだor2,勇なまor2,ゆうしゃのくせになまいきだor2,ゆうなまor2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2008-10-16").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "テイルズオブザワールド レディアントマイソロジー3",
    keyword: "ているずおぶざわーるどれでぃあんとまいそろじー3,まいそろ3,towrm3",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2011-02-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "俺の屍を越えてゆけ",
    keyword: "俺の屍を越えてゆけ,俺屍,おれのしかばねをこえてゆけ,おれしか",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2011-11-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PSP",
    title: "ファンタシースターポータブル 2 インフィニティ",
    keyword: "ふぁんたしーすたーぽーたぶる2いんふぃにてぃ,pspo2i,psp2i,psp2∞",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "武器集め,PAディスク集め..etc",
    release_date: new Date("2011-02-24").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "ラチェット&クランク2 ガガガ!銀河のコマンドーっす",
    keyword: "らちぇっと&くらんく,らちぇっとあんどくらんく,らちぇくら",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2003-11-11").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "ラチェット&クランク4th ギリギリ銀河のギガバトル",
    keyword: "らちぇっと&くらんく,らちぇっとあんどくらんく,らちぇくら",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "バトルボット",
    release_date: new Date("2005-11-23").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "我が竜を見よ",
    keyword: "我が竜を見よ,わがりゅうをみよ",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "ハヤブサ",
    release_date: new Date("2004-10-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "真・三國無双",
    keyword: "真・三國無双,さんごくむそう",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "呂布🤬",
    release_date: new Date("2000-08-03").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "真・三國無双2",
    keyword: "真・三國無双2,さんごくむそう2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2001-09-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "真・三國無双4 猛将伝",
    keyword: "真・三國無双4,さんごくむそう4",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "立志モードが神",
    release_date: new Date("2005-09-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "決戦III",
    keyword: "決戦3,けっせん3",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2004-12-22").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS2",
    title: "FINAL FANTASY XII",
    keyword: "finalfantasy12,ff12,ふぁいなるふぁんたじー12",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "初FF,ヤズマット等は未討伐",
    release_date: new Date("2006-03-16").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "魔界戦記ディスガイア4",
    keyword: "魔界戦記でぃすがいあ4,まかいせんきでぃすがいあ4",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "界賊船パーツ...",
    release_date: new Date("2011-02-24").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "モンスターハンターポータブル 3rd HD ver.",
    keyword: "もんすたーはんたーぽーたぶる3rd,もんはん3rd,mhp3rd",
    completed: false,
    achievement: "T5K9",
    playtime: 408,
    archive_url: "",
    notes: "弓",
    release_date: new Date("2011-08-25").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "アサシンクリード III",
    keyword: "あさしんくりーど3,あさくり3",
    completed: true,
    achievement: "トロコン",
    playtime: 22,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-11-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "アサシンクリード リベレーション",
    keyword: "あさしんくりーどりべれーしょん,あさくりりべれーしょん",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2011-12-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "テイルズ オブ グレイセス エフ",
    keyword: "ているずおぶぐれいせすf,ているずおぶぐれいせすえふ,togf",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "ヒューバート",
    release_date: new Date("2010-12-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "Demon's Souls",
    keyword: "demonssouls,でもんずそうる",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "月光剣,浮遊ソウル,火の玉",
    release_date: new Date("2009-02-05").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "テイルズ オブ ゼスティリア",
    keyword: "ているずおぶぜすてぃりあ,toz",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-01-22").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "WATCH DOGS",
    keyword: "watchdogs,うぉっちどっぐす",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2014-05-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "テイルズ オブ エクシリア 2",
    keyword: "ているずおぶえくしりあ2,tox2",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-11-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "METAL GEAR SOLID V: THE PHANTOME PAIN",
    keyword: "metalgearsolid5,めたるぎあそりっど5,mgs5",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-09-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "Diablo III",
    keyword: "diablo3,でぃあぶろ3",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "タルラシャメテオ",
    release_date: new Date("2012-05-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "アサシンクリード IV ブラックフラッグ",
    keyword: "あさしんくりーど4ぶらっくふらっぐ,あさくり4ぶらっくふらっぐ",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "海戦おもしろい",
    release_date: new Date("2013-11-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "Grand Theft Auto V",
    keyword: "grandtheftauto5,ぐらんどせふとおーと5,ぐらせふ5,gta5",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2013-10-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "Dragon's Dogma: Dark Arisen",
    keyword: "dragonsdogma,どらごんずどぐま",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-05-22").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "Dead Rising 2",
    keyword: "deadrising2,でっどらいじんぐ2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-09-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "STAROCEAN THE LAST HOPE -INTERNATIONAL-",
    keyword: "starocean,すたーおーしゃん",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2010-02-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "テイルズ オブ エクシリア",
    keyword: "ているずおぶえくしりあ,tox",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2011-09-08").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "KINGDOM HEARTS 358/2 Days",
    keyword: "kingdomhearts,きんぐだむはーつ,kh",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2013-03-14").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "バイナリー ドメイン",
    keyword: "ばいなりーどめいん",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-02-16").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "真・三國無双6 猛将伝",
    keyword: "真・三國無双6,さんごくむそう6",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2011-09-29").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "METAL GEAR SOLID 4",
    keyword: "metalgearsolid4,めたるぎあそりっど4,mgs4",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "オンラインのMGO2も面白い",
    release_date: new Date("2008-06-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "FINAL FANTASY XIII",
    keyword: "finalfantasy13,ふぁいなるふぁんたじー13,ff13",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "ファング",
    release_date: new Date("2009-12-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "NBA 2K13",
    keyword: "nba2k13",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-10-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "Grand Theft Auto IV",
    keyword: "grandtheftauto4,ぐらんどせふとおーと4,ぐらせふ4,gta4",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2008-04-29").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "KINGDOM HEARTS Re:Chain of Memories",
    keyword: "kingdomhearts,きんぐだむはーつ,kh",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2013-03-14").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "KINGDOM HEARTS FINAL MIX",
    keyword: "kingdomhearts,きんぐだむはーつ,kh",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "バンビ召喚して魔法連打",
    release_date: new Date("2013-03-14").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "Borderlands",
    keyword: "borderlands,ぼーだーらんず,ぼだらん",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "セイレーンのリリス",
    release_date: new Date("2009-10-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "DARK SOULS",
    keyword: "darksouls,だーくそうる,だくそ",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2011-09-22").getTime(),
    createdAt: Date.now(),
  },
    {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "アサシンクリード",
    keyword: "あさしんくりーど,あさくり",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "初アサクリ",
    release_date: new Date("2007-11-29").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "アサシンクリード II",
    keyword: "あさしんくりーど2,あさくり2",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "神",
    release_date: new Date("2009-12-03").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "アサシンクリード ブラザーフッド",
    keyword: "あさしんくりーどぶらざーふっど,あさくりぶらざーふっど",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "弟子のアサシンを呼び出せる",
    release_date: new Date("2010-12-09").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "NBA 2K12",
    keyword: "nba2k12",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2011-10-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS3",
    title: "テイルズ オブ ヴェスペリア",
    keyword: "ているずおぶゔぇすぺりあ,tov",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "ジュディス",
    release_date: new Date("2009-09-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Diablo III: Reaper of Souls",
    keyword: "diablo3,でぃあぶろ3",
    completed: true,
    achievement: "トロコン",
    playtime: 286,
    archive_url: "",
    notes: "パラゴン900",
    release_date: new Date("2014-03-25").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Cities: Skylines",
    keyword: "citiesskylines,してぃーずすかいらいん",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-03-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Borderlands 3",
    keyword: "borderlands3,ぼーだーらんず3,ぼだらん3",
    completed: true,
    achievement: "トロコン",
    playtime: 72,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-09-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "GOD EATER 2 RAGE BURST",
    keyword: "godeater2rageburst,ごっどいーたー2れいじばーすと",
    completed: true,
    achievement: "トロコン",
    playtime: 155,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-02-19").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "GOD EATER 3",
    keyword: "godeater3,ごっどいーたー3",
    completed: true,
    achievement: "トロコン",
    playtime: 59,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-12-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Minecraft Dungeons",
    keyword: "minecraftdungeons,まいんくらふとだんじょんず,まいくらだんじょんず",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2020-05-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "SEKIRO: SHADOWS DIE TWICE",
    keyword: "隻狼,sekiro,せきろう",
    completed: true,
    achievement: "一心ルートクリア",
    playtime: 49,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-03-22").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "BIOMUTANT",
    keyword: "biomutant,ばいおみゅーたんと",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "途中でやめた",
    release_date: new Date("2021-05-25").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アサシンクリード オリジンズ",
    keyword: "あさしんくりーどおりじんず,あさくりおりじんず",
    completed: true,
    achievement: "トロコン",
    playtime: 52,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-10-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ゆけむり温泉郷",
    keyword: "ゆけむり温泉郷,ゆけむりおんせんきょう,かいろそふと",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-12-05").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "冒険ダンジョン村",
    keyword: "冒険ダンジョン村,ぼうけんだんじょんむら,かいろそふと",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-12-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ゲーム発展国++",
    keyword: "ゲーム発展国++,げーむはってんこく++,かいろそふと",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-12-05").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "モンスターハンターワールド:アイスポーン",
    keyword: "もんすたーはんたーわーるどあいすぼーん,もんはんわーるどあいすぼーん,あいぼ,mhwi",
    completed: false,
    achievement: "MR300弱",
    playtime: 783,
    archive_url: "",
    notes: "弓,たまにライト,ミラ未討伐",
    release_date: new Date("2019-09-06").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Horizon Zero Dawn",
    keyword: "horizonzerodawn,ほらいぞんぜろどーん",
    completed: true,
    achievement: "クリア",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-03-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "DETROIT: BECOME HUMAN",
    keyword: "detroitbecomehuman,でとろいとびかむひゅーまん",
    completed: true,
    achievement: "トロコン",
    playtime: 30,
    archive_url: "",
    notes: "パーキンス(FBI捜査官)に騙されて全滅",
    release_date: new Date("2018-05-25").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "SherlockHolmes: The Devil's Daughter",
    keyword: "sherlockHolmes,しゃーろっくほーむず",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-06-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ABZU",
    keyword: "abzu",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-08-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アッシュと魔法の筆",
    keyword: "あっしゅと魔法の筆,あっしゅとまほうのふで",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-10-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Borderlands: The Pre-Sequel",
    keyword: "borderlandsthepresequel,ぼーだーらんずぷりしーくえる,ぼだらんぷりしーくえる",
    completed: true,
    achievement: "クリア",
    playtime: 58,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-03-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "真・三國無双7 with 猛将伝",
    keyword: "真・三國無双7,さんごくむそう7",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2014-02-22").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "NARUT0-ナルト-疾風伝 ナルティメットストーム 4",
    keyword: "なると,なるてぃめっとすとーむ4",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-02-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "TomClancy's The Division 2",
    keyword: "division2,でぃびじょん2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-03-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ロケットリーグ",
    keyword: "rocketleague,ろけっとりーぐ,ろけり",
    completed: false,
    achievement: "@1でトロコン",
    playtime: 50,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-11-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "進撃の巨人 2",
    keyword: "進撃の巨人2,しんげきのきょじん2",
    completed: true,
    achievement: "",
    playtime: 36,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-03-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アサシンクリード レディリバティ",
    keyword: "あさしんくりーどれでぃりばてぃ,あさくりれでぃりばてぃ",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-11-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ゴーストリコン ブレイクポイント",
    keyword: "ごーすとりこんぶれいくぽいんと",
    completed: true,
    achievement: "トロコン",
    playtime: 75,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-10-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "NBA 2K21",
    keyword: "nba2k21",
    completed: false,
    achievement: "",
    playtime: 92,
    archive_url: "",
    notes: "",
    release_date: new Date("2020-09-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "テラリア",
    keyword: "terraria,てらりあ",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "ちょっとだけ",
    release_date: new Date("2015-02-19").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ペルソナ 5",
    keyword: "persona5,ぺるそな5",
    completed: true,
    achievement: "クリア",
    playtime: 131,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-09-15").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "フォールガイズ",
    keyword: "fallguys,ふぉーるがいず",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2020-08-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "NBA 2K20",
    keyword: "nba2k20",
    completed: false,
    achievement: "",
    playtime: 427,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-09-06").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "NieR: Automata",
    keyword: "nierautomata,にーあおーとまた",
    completed: true,
    achievement: "トロコン",
    playtime: 32,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-02-23").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Nippon Marathon",
    keyword: "nipponmarathon,にっぽんまらそん",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-12-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ウィッチャー3 ワイルドハント",
    keyword: "witcher3,うぃっちゃー3",
    completed: true,
    achievement: "",
    playtime: 118,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-05-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アサシンクリード オデッセイ",
    keyword: "あさしんくりーどおでっせい,あさくりおでっせい",
    completed: true,
    achievement: "トロコン",
    playtime: 210,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-10-05").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アサシンクリード ユニティ",
    keyword: "あさしんくりーどゆにてぃ,あさくりゆにてぃ",
    completed: true,
    achievement: "トロコン",
    playtime: 138,
    archive_url: "",
    notes: "CO-OPミッションがおもしろい",
    release_date: new Date("2014-11-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アサシンクリード シンジケート",
    keyword: "あさしんくりーどしんじけーと,あさくりしんじけーと",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-11-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "シャドウ・オブ・ウォー",
    keyword: "しゃどうおぶうぉー",
    completed: true,
    achievement: "トロコン",
    playtime: 76,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-10-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "バトルフィールド ハードライン",
    keyword: "ばとるふぃーるどはーどらいん",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-03-19").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "WATCH DOGS 2",
    keyword: "watchdogs2,うぉっちどっぐす2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-12-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "The Sims 4",
    keyword: "sims4,しむず4",
    completed: true,
    achievement: "トロコン",
    playtime: 67,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-11-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Call of Duty: WW II",
    keyword: "codww2,こーるおぶでゅーてぃww2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "キャンペーンのみ",
    release_date: new Date("2017-11-03").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ニノ国 白き聖灰の女王 リマスタード",
    keyword: "にのくに",
    completed: true,
    achievement: "クリア",
    playtime: 62,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-09-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ラチェット&クランク THE GAME",
    keyword: "らちぇっと&くらんく,らちぇっとあんどくらんく,らちぇくら",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-04-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Marvel's Spider-Man",
    keyword: "spiderman,すぱいだーまん",
    completed: true,
    achievement: "トロコン",
    playtime: 46,
    archive_url: "",
    notes: "とにかく移動が楽しい！",
    release_date: new Date("2018-09-07").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ワンダと巨像",
    keyword: "わんだときょぞう",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-02-08").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ワンピース海賊無双 3",
    keyword: "わんぴーす海賊無双3,わんぴーすかいぞくむそう3",
    completed: false,
    achievement: "",
    playtime: 46,
    archive_url: "",
    notes: "量が多くてトロコン断念",
    release_date: new Date("2015-03-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アンチャーテッド エル・ドラドの秘宝 リマスタード",
    keyword: "あんちゃーてっどエルドラドの秘宝,あんちゃーてっどえるどらどのひほう,あんちゃ",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アンチャーテッド 黄金刀と消えた船団 リマスタード",
    keyword: "あんちゃーてっど黄金刀と消えた船団,あんちゃーてっどおうごんとうときえたせんだん,あんちゃ",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アンチャーテッド 砂漠に眠るアトランティス リマスタード",
    keyword: "あんちゃーてっど砂漠に眠るアトランティス,あんちゃーてっどさばくにねむるあとらんてぃす,あんちゃ",
    completed: true,
    achievement: "",
    playtime: 38,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-11-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "アンチャーテッド 海賊王と最後の秘宝",
    keyword: "あんちゃーてっど海賊王と最後の秘宝,あんちゃーてっどかいぞくおうとさいごのひほう,あんちゃ",
    completed: true,
    achievement: "",
    playtime: 23,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-05-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Goat Simulator",
    keyword: "goatsimulator,ごーとしみゅれーたー",
    completed: true,
    achievement: "トロコン",
    playtime: 100,
    archive_url: "",
    notes: "フラッピーヤギがキツかった",
    release_date: new Date("2015-10-07").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "トロピコ 5",
    keyword: "tropico5,とろぴこ5",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-04-23").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "CONTROL",
    keyword: "control,こんとろーる",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-12-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Skyrim",
    keyword: "skyrim,すかいりむ",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-11-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ドラゴンクエストビルダーズ 2 破壊神シドーとからっぽの島",
    keyword: "どらごんくえすとびるだーず2,どらくえびるだーず2,dqb2",
    completed: true,
    achievement: "トロコン",
    playtime: 103,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-12-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "JUMP FORCE",
    keyword: "jumpforce,じゃんぷふぉーす",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "キルア",
    release_date: new Date("2019-02-14").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ドーントレス",
    keyword: "dauntless,どーんとれす",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "カウンター楽しい",
    release_date: new Date("2019-12-11").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Borderlands 2",
    keyword: "borderlands2,ぼーだーらんず2,ぼだらん2",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "セイレーンのマヤ",
    release_date: new Date("2017-03-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "タイタンフォール 2",
    keyword: "titanfall2,たいたんふぉーる2",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-10-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ロロナのアトリエーアーランドの錬金術士ーDX",
    keyword: "ろろなのあとりえ",
    completed: false,
    achievement: "ノーマルエンド",
    playtime: 25,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-09-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "仁王",
    keyword: "仁王,におう",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-02-09").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "ドラゴンエイジ: インクイジション",
    keyword: "どらごんえいじいんくいじしょん",
    completed: false,
    achievement: "",
    playtime: 40,
    archive_url: "",
    notes: "上級クラスは解放した",
    release_date: new Date("2014-11-27").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "The Last of Us Remastered",
    keyword: "lastofus,らすとおぶあす",
    completed: true,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2014-08-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "DAYS GONE",
    keyword: "daysgone,でいずごーん",
    completed: false,
    achievement: "",
    playtime: 28,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-04-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "テイルズ オブ ベルセリア",
    keyword: "ているずおぶべるせりあ,tob",
    completed: true,
    achievement: "",
    playtime: 59,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-08-18").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Call of Duty: BlackOps III",
    keyword: "callofdutyblackops3,こーるおぶでゅーてぃぶらっくおぷす3,codbo3",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-11-06").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Dead Rising",
    keyword: "deadrising,でっどらいじんぐ",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-09-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Dead Rising 2 Off The Record",
    keyword: "deadrising2,でっどらいじんぐ2",
    completed: false,
    achievement: "",
    playtime: 10,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-09-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Red Dead Redemption 2",
    keyword: "reddeadredemption2,れっどでっどれでんぷしょん2",
    completed: true,
    achievement: "",
    playtime: 84,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-10-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "NBA 2K18",
    keyword: "nba2k18",
    completed: false,
    achievement: "",
    playtime: 414,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-09-19").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "フォートナイト",
    keyword: "fortnite,ふぉーとないと",
    completed: false,
    achievement: "",
    playtime: 176,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-07-25").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "FINALFANTASY XV",
    keyword: "finalfantasy15,ふぁいなるふぁんたじー15,ff15",
    completed: true,
    achievement: "",
    playtime: 26,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-11-29").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "3on3 FreeStyle",
    keyword: "3on3freestyle,3on3ふりーすたいる,ふりすた",
    completed: false,
    achievement: "",
    playtime: 55,
    archive_url: "",
    notes: "",
    release_date: new Date("2017-04-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "FINAL FANTASY XII THE ZODIAC AGE",
    keyword: "finalfantasy12tza,ふぁいなるふぁんたじー12tza,ff12tza",
    completed: false,
    achievement: "",
    playtime: 31,
    archive_url: "",
    notes: "シド倒した",
    release_date: new Date("2017-07-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "STAR WARS バトルフロント",
    keyword: "starwarsbattlefront,すたーうぉーずばとるふろんと,swbf",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "",
    release_date: new Date("2015-11-19").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Just Cause 3",
    keyword: "justcause3,じゃすとこーず3",
    completed: false,
    achievement: "クリア",
    playtime: 49,
    archive_url: "",
    notes: "",
    release_date: new Date("2016-01-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "DARK SOULS II SCHOLAR OF THE FIRSTE SIN",
    keyword: "darksouls2,だーくそうる2,だくそ2",
    completed: false,
    achievement: "",
    playtime: 44,
    archive_url: "",
    notes: "三つ子は倒した",
    release_date: new Date("2015-04-09").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS4",
    title: "Bloodborne",
    keyword: "bloodborne,ぶらっどぼーん,ぶらぼ",
    completed: true,
    achievement: "",
    playtime: 147,
    archive_url: "",
    notes: "ゲールマン",
    release_date: new Date("2015-03-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS5",
    title: "NBA 2K22",
    keyword: "nba2k22",
    completed: false,
    achievement: "",
    playtime: 161,
    archive_url: "",
    notes: "",
    release_date: new Date("2021-09-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS5",
    title: "NBA 2K21",
    keyword: "nba2k21",
    completed: false,
    achievement: "",
    playtime: 116,
    archive_url: "",
    notes: "",
    release_date: new Date("2020-11-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PS5",
    title: "アサシンクリード ヴァルハラ",
    keyword: "あさしんくりーどゔぁるはら,あさくりゔぁるはら",
    completed: true,
    achievement: "",
    playtime: 61,
    archive_url: "",
    notes: "",
    release_date: new Date("2020-11-12").getTime(),
    createdAt: Date.now(),
  },
    {
    id: crypto.randomUUID(),
    hardware: "PS5",
    title: "モンスターハンターワイルズ",
    keyword: "もんすたーはんたー,もんはんわいるず,mhwilds",
    completed: false,
    achievement: "",
    playtime: 85,
    archive_url: "",
    notes: "",
    release_date: new Date("2025-02-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Mobile",
    title: "サマナーズウォー",
    keyword: "さまなーずうぉー",
    completed: false,
    achievement: "闇ストライカー,光キメラ",
    playtime: 3000,
    archive_url: "",
    notes: "たまに遊んでる",
    release_date: new Date("2014-06-12").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Mobile",
    title: "パズル&ドラゴンズ",
    keyword: "ぱずる&どらごんず,ぱずどら",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "2014年くらいまで",
    release_date: new Date("2012-02-20").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PC",
    title: "RED STONE",
    keyword: "redstone,れっどすとーん,あかいし,rs",
    completed: false,
    achievement: "",
    playtime: 20000,
    archive_url: "",
    notes: "エンヘイおね^^",
    release_date: new Date("2004-12-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PC",
    title: "マインクラフト",
    keyword: "minecraft,まいんくらふと,まいくら",
    completed: false,
    achievement: "エンドラ討伐",
    playtime: 100,
    archive_url: "",
    notes: "たまに遊んでる",
    release_date: new Date("2011-11-18").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PC",
    title: "FINAL FANTASY XIV",
    keyword: "finalfantasy14,ff14,ふぁいなるふぁんたじー14,ふぉーてぃーん",
    completed: false,
    achievement: "新生エオルゼア編クリア",
    playtime: 100,
    archive_url: "",
    notes: "侍",
    release_date: new Date("2013-08-27").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PC",
    title: "原神",
    keyword: "原神,げんしん",
    completed: false,
    achievement: "Rank60",
    playtime: 3000,
    archive_url: "",
    notes: "アリス",
    release_date: new Date("2020-09-28").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PC",
    title: "崩壊:スターレイル",
    keyword: "崩壊すたーれいる,ほうかいすたーれいる,すたれ",
    completed: false,
    achievement: "Rank70",
    playtime: 2000,
    archive_url: "",
    notes: "KFK",
    release_date: new Date("2023-04-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PC",
    title: "ゼンレスゾーンゼロ",
    keyword: "ぜんれすぞーんぜろ,ぜんぜろ,zzz",
    completed: false,
    achievement: "Rank50",
    playtime: 1000,
    archive_url: "",
    notes: "星見雅",
    release_date: new Date("2024-07-04").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "PC",
    title: "VALORANT",
    keyword: "valorant,ゔぁろらんと",
    completed: false,
    achievement: "",
    playtime: 100,
    archive_url: "",
    notes: "たまにTDM,DM",
    release_date: new Date("2020-06-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Star Wars バトルフロント II",
    keyword: "すたーうぉーずばとるふろんと2,swbf2",
    completed: true,
    achievement: "全アビリティ解放",
    playtime: 129,
    archive_url: "",
    notes: "たまに遊んでるお祭りゲー",
    release_date: new Date("2017-11-16").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "モンスターハンターワールド：アイスボーン",
    keyword: "もんすたーはんたー,もんはんわーるど,もんはんあいすぼーん,あいぼ,mhwi",
    completed: false,
    achievement: "",
    playtime: 146,
    archive_url: "",
    notes: "太刀メイン",
    release_date: new Date("2018-08-10").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "モンスターハンターライズ:サンブレイク",
    keyword: "もんすたーはんたーらいず:さんぶれいく,もんはんらいず,もんはんさんぶれいく,mhrs",
    completed: false,
    achievement: "",
    playtime: 168,
    archive_url: "",
    notes: "太刀",
    release_date: new Date("2022-01-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Raft",
    keyword: "らふと,raft",
    completed: false,
    achievement: "",
    playtime: 18,
    archive_url: "",
    notes: "船辺りで止まってる",
    release_date: new Date("2022-06-21").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Rimworld",
    keyword: "りむわーるど,rimworld",
    completed: false,
    achievement: "",
    playtime: 190,
    archive_url: "",
    notes: "",
    release_date: new Date("2018-10-17").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "パルワールド",
    keyword: "ぱるわーるど,palworld",
    completed: false,
    achievement: "",
    playtime: 69,
    archive_url: "",
    notes: "ジェッドランは捕獲済み",
    release_date: new Date("2024-01-19").getTime(),
    createdAt: Date.now(),
  },
    {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "ウルトラストリートファイター4",
    keyword: "うるとらすとりーとふぁいたー4,うる4,すと4,sf4",
    completed: false,
    achievement: "",
    playtime: 55,
    archive_url: "",
    notes: "スト6のヴァイパーに備えて395円で購入",
    release_date: new Date("2014-08-07").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "ストリートファイター6",
    keyword: "すとりーとふぁいたー6,すと6,sf6",
    completed: false,
    achievement: "認定シルバー、トレモ勢",
    playtime: 1000,
    archive_url: "",
    notes: "Cキンバリー,Cキャミィ",
    release_date: new Date("2023-06-02").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Borderlands 2",
    keyword: "borderlands2,ぼーだーらんず2,ぼだらん2",
    completed: false,
    achievement: "",
    playtime: 50,
    archive_url: "",
    notes: "",
    release_date: new Date("2012-10-26").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Citadel: Forged with Fire",
    keyword: "citadel,したでる",
    completed: false,
    achievement: "",
    playtime: 14,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-11-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Destiny 2",
    keyword: "destiny2,ですてぃにー2",
    completed: false,
    achievement: "",
    playtime: 13,
    archive_url: "",
    notes: "",
    release_date: new Date("2019-10-01").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "ELDEN RING NIGHTREIGN",
    keyword: "eldenringnightreign,えるでんりんぐないとれいん",
    completed: false,
    achievement: "",
    playtime: 20,
    archive_url: "",
    notes: "",
    release_date: new Date("2025-05-30").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "THE FINALS",
    keyword: "thefinals,ふぁいなるず",
    completed: false,
    achievement: "",
    playtime: 10,
    archive_url: "",
    notes: "建物破壊可能FPS",
    release_date: new Date("2023-12-08").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "God Of Weapons",
    keyword: "godofweapons,ごっどおぶうぇぽんず",
    completed: false,
    achievement: "",
    playtime: 13,
    archive_url: "",
    notes: "",
    release_date: new Date("2023-09-13").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "GRANBLUE FANTASY: Relink",
    keyword: "granbluefantasyrelink,ぐらんぶるーふぁんたじーりりんく",
    completed: false,
    achievement: "",
    playtime: 13,
    archive_url: "",
    notes: "",
    release_date: new Date("2024-02-01").getTime(),
    createdAt: Date.now(),
  },
    {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Mount & Blade II: Bannerlord",
    keyword: "mount&blade2,まうんと&ぶれーど,まうんとあんどぶれーど",
    completed: false,
    achievement: "",
    playtime: 192,
    archive_url: "",
    notes: "",
    release_date: new Date("2022-10-25").getTime(),
    createdAt: Date.now(),
  },
    {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Warlander",
    keyword: "warlander,うぉーらんだー",
    completed: false,
    achievement: "",
    playtime: 101,
    archive_url: "",
    notes: "",
    release_date: new Date("2023-01-25").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "Apex Legends",
    keyword: "apexlegends,えーぺっくすれじぇんず,えぺ",
    completed: false,
    achievement: "",
    playtime: 82,
    archive_url: "",
    notes: "射撃訓練場だけ",
    release_date: new Date("2020-11-05").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "鳴潮",
    keyword: "鳴潮,めいちょう",
    completed: false,
    achievement: "",
    playtime: 55,
    archive_url: "",
    notes: "長離",
    release_date: new Date("2024-05-23").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "サマナーズウォー",
    keyword: "さまなーずうぉー",
    completed: false,
    achievement: "",
    playtime: 1000,
    archive_url: "",
    notes: "",
    release_date: new Date("2024-01-08").getTime(),
    createdAt: Date.now(),
  },
  {
    id: crypto.randomUUID(),
    hardware: "Steam",
    title: "サマナーズウォー：クロニクル",
    keyword: "さまなーずうぉーくろにくる",
    completed: false,
    achievement: "",
    playtime: 465,
    archive_url: "",
    notes: "",
    release_date: new Date("2022-11-10").getTime(),
    createdAt: Date.now(),
  },
];

// --- ユーティリティ ---
const uniq = (arr: string[]) => Array.from(new Set(arr.filter(Boolean)));

// カタカナをひらがなに変換する関数
function toHiragana(input: string): string {
  return input
    .normalize("NFKC") // 全角/半角を統一
    .replace(/[\u30a1-\u30f6]/g, (match) =>
      String.fromCharCode(match.charCodeAt(0) - 0x60)
    );
}

// --- メインコンポーネント ---
export default function GameLog() {
  const [rows, setRows] = useState<GameItem[]>(seedData);
  const [query, setQuery] = useState("");
  const [hardwareFilter, setHardwareFilter] = useState<string>("all");
  const [completedFilter, setCompletedFilter] = useState<string>("all");
  const [sortKey, setSortKey] = useState<string>("releaseDate_asc");
  const hardwareList = useMemo(
    () => uniq(rows.map((r) => r.hardware)).sort(),
    [rows]
  );

  const filtered = useMemo(() => {
    const q = toHiragana(query.trim().toLowerCase());
    let out = rows.filter((r) => {
      const okHardware = hardwareFilter === "all" || r.hardware === hardwareFilter;
      const okCompleted =
        completedFilter === "all" || (completedFilter === "done" ? r.completed : !r.completed);
      const keywordHira = toHiragana(r.keyword.toLowerCase());
      const okQuery = !q ||
        keywordHira.includes(q);
        // (r.achievement ?? "").toLowerCase().includes(q) ||
        // (r.notes ?? "").toLowerCase().includes(q) ||
      // r.hardware.toLowerCase().includes(q);
      return okHardware && okCompleted && okQuery;
    });

    switch (sortKey) {
      case "releaseDate_desc":
        out.sort((a, b) => b.release_date - a.release_date); break;
      case "releaseDate_asc":
        out.sort((a, b) => a.release_date - b.release_date); break;
      case "title_asc":
        out.sort((a, b) => a.title.localeCompare(b.title)); break;
      case "title_desc":
        out.sort((a, b) => b.title.localeCompare(a.title)); break;
      case "playtime_desc":
        out.sort((a, b) => b.playtime - a.playtime); break;
      case "playtime_asc":
        out.sort((a, b) => a.playtime - b.playtime); break;
    }
    return out;
  }, [rows, query, hardwareFilter, completedFilter, sortKey]);

  return (
    <div className="min-h-screen bg-gradient-to-b from-slate-50 to-white p-4 md:p-8">
      <motion.div initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 1.2 }} className="max-w-6xl mx-auto space-y-4">
        <header className="flex flex-col md:flex-row md:items-end gap-3 md:gap-4">
          <div className="flex-1 space-y-1">
            <h1 className="text-2xl md:text-3xl font-bold tracking-tight flex items-center gap-2">
              <Gamepad2 className="w-7 h-7" />
            </h1>
            <p className="text-sm text-muted-foreground">今まで遊んできたゲーム</p>
          </div>
        </header>

        <Card className="border-0 shadow-sm">
          <CardContent className="p-4 md:p-6 space-y-4">
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
              <div className="md:col-span-2">
                <div className="relative">
                  <Search className="w-4 h-4 absolute left-2 top-1/2 -translate-y-1/2" />
                  <Input className="pl-8" placeholder="検索（ゲームソフト名）" value={query} onChange={(e) => setQuery(e.target.value)} />
                </div>
              </div>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
              {/* ハードでのフィルター */}
              <div className="flex items-center gap-2">
                <Select value={hardwareFilter} onValueChange={setHardwareFilter}>
                  <SelectTrigger className="w-full"><SelectValue placeholder="ハード" /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">全てのハード</SelectItem>
                    {hardwareList.map((h) => (
                      <SelectItem key={h} value={h}>{h}</SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>
              {/* クリア有無でのフィルター */}
              <div className="flex items-center gap-2">
                <Tabs value={completedFilter} onValueChange={setCompletedFilter} className="w-full">
                  <TabsList className="grid grid-cols-3 w-full">
                    <TabsTrigger value="all">全て</TabsTrigger>
                    <TabsTrigger value="done">クリア済</TabsTrigger>
                    <TabsTrigger value="todo">未クリア</TabsTrigger>
                  </TabsList>
                </Tabs>
              </div>
              {/* 並び替え */}
              <div className="flex items-center gap-2 md:col-start-4">
                {/* <span className="text-sm text-muted-foreground">並び替え:</span> */}
                <ArrowDownWideNarrow  className="w-4 h-4" />
                <Select value={sortKey} onValueChange={setSortKey}>
                  <SelectTrigger className="w-[220px]"><SelectValue /></SelectTrigger>
                  <SelectContent>
                    <SelectItem value="releaseDate_desc">発売日(新)</SelectItem>
                    <SelectItem value="releaseDate_asc">発売日(旧)</SelectItem>
                    <SelectItem value="playtime_desc">プレイ時間(多)</SelectItem>
                    <SelectItem value="playtime_asc">プレイ時間(少)</SelectItem>
                    <SelectItem value="title_asc">タイトル A→Z</SelectItem>
                    <SelectItem value="title_desc">タイトル Z→A</SelectItem>
                  </SelectContent>
                </Select>
                <div className="ml-auto" />
              </div>
            </div>

            {/* 合計プレイ時間と検索件数を表示する */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-3">
              <div className="flex gap-3 md:col-start-4">
                {/* 合計プレイ時間 */}
                <span className="text-sm text-muted-foreground">
                  {filtered.reduce((sum, r) => sum + r.playtime, 0).toLocaleString('ja-JP')} 時間
                </span>
                {/* 検索件数 */}
                <span className="text-sm text-muted-foreground justify-end">
                  {filtered.length} 件
                </span>
              </div>
            </div>

            <div className="rounded-2xl border overflow-hidden overflow-x-auto">
              <Table className="min-w-[600px]">
                <TableHeader>
                  <TableRow>
                    <TableHead className="w-[80px]">ハード名</TableHead>
                    <TableHead className="text-center">ゲーム名</TableHead>
                    <TableHead className="w-[70px] text-center">クリア</TableHead>
                    <TableHead className="w-[110px] text-center">プレイ時間</TableHead>
                    <TableHead className="text-center">アチーブメント</TableHead>
                    <TableHead className="text-center">備考</TableHead>
                    <TableHead className="text-center">URL</TableHead>
                    {/* <TableHead className="w-[110px]"></TableHead> */}
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {filtered.map((r) => (
                    <TableRow key={r.id} className="hover:bg-slate-50">
                      <TableCell>
                        <Badge variant="secondary" className="text-xs py-1 px-2 rounded-xl">{r.hardware}</Badge>
                      </TableCell>
                      <TableCell className="font-medium">{r.title}</TableCell>
                      <TableCell className="text-center">{r.completed ? "✔" : "-"}</TableCell>
                      <TableCell className="text-sm text-center">{r.playtime.toLocaleString('ja-JP')}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">{r.achievement || ""}</TableCell>
                      <TableCell className="text-sm text-muted-foreground">{r.notes || ""}</TableCell>
                      <TableCell className="text-sm text-center">
                        {r.archive_url.length !== 0 && (
                          <a target="_blank" href={"" + r.archive_url}><ExternalLink className="w-4 h-4"/></a>
                        )}
                      </TableCell>
                    </TableRow>
                  ))}
                  {filtered.length === 0 && (
                    <TableRow>
                      <TableCell colSpan={8} className="text-center text-sm text-muted-foreground py-8">該当するデータがありません</TableCell>
                    </TableRow>
                  )}
                </TableBody>
              </Table>
            </div>
          </CardContent>
        </Card>

        <footer className="text-xs text-muted-foreground text-right"></footer>
      </motion.div>
    </div>
  );
}
